spring:
    application:
        name: account-service
    datasource:
        url: jdbc:postgresql://localhost:5432/account
        username: postgres
        password: huypd123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true
                dialect: org.hibernate.dialect.PostgreSQLDialect

    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            properties:
                spring.json.add.type.headers: false

# 4. CẤU HÌNH REDIS (THÊM MỚI VÀO ĐÂY)
    data:
        redis:
            host: localhost       # Địa chỉ Redis Server
            port: 6379            # Port mặc định của Redis
            password:             # Để trống nếu không đặt mật khẩu
            database: 0           # Redis có 16 DB (0-15), chọn cái số 0
            # Timeout khi kết nối (tùy chọn)
            connect-timeout: 2s
            timeout: 1s
    cache:
        type: redis             # Báo cho Spring Boot biết dùng Redis làm Cache Manager
        redis:
            time-to-live: 600000  # (Tùy chọn) Thời gian sống của cache (ms). Ví dụ: 10 phút.
            cache-null-values: false # Không cache các giá trị null
# 5. CẤU HÌNH SERVER (THÊM CỔNG VÀO ĐÂY)
server:
    port: 10001 # Chọn một cổng khác 8080 để tránh xung đột