spring:
    application:
        name: notification-service
    main:
        allow-bean-definition-overriding: true
    datasource:
        url: jdbc:postgresql://localhost:5432/notification
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 5000
            maximum-pool-size: 5

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    kafka:
        bootstrap-servers: localhost:9092

        consumer:
            group-id: notification-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
    data:
        redis:
            host: localhost
            port: 6379
            database: 1 # Bạn có thể chọn DB khác (VD: 1) để không lẫn với Transaction Service
    cache:
        type: redis
        redis:
            time-to-live: 86400000 # 1 ngày (24h). Account Number ít đổi nên để lâu được.
            cache-null-values: false # Không lưu nếu không tìm thấy User

# Custom Config
application:
  topics:
    transaction-events: transaction-topic # Tên chuẩn

server:
    port: 10005

# --- PHẦN THÊM MỚI ---

# 1. Cấu hình Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Đổi nếu Eureka chạy port khác
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true # QUAN TRỌNG: Cho phép Eureka kiểm tra trạng thái thật của app (DB, Redis...)

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 # Gửi tim (heartbeat) mỗi 10s
    lease-expiration-duration-in-seconds: 30

# 2. Cấu hình Actuator (Health Check)
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics # Mở các cổng cần thiết
  endpoint:
    health:
      show-details: always # Hiển thị chi tiết (DB up/down, Redis up/down)
  health:
    circuitbreakers:
      enabled: true