server:
  port: 10003
  # QUAN TRỌNG KHI LÊN CLOUD: 
  # Giúp Gateway hiểu nó đang đứng sau Proxy (Cloudflare/Nginx)
  # để xử lý đúng các đường dẫn chuyển hướng (Redirect URI) trong OAuth2.
  forward-headers-strategy: native 

spring:
  application:
    name: gateway-service
  
  # Tăng kích thước bộ đệm cho Header (Tránh lỗi Header quá dài khi dùng JWT Token lớn)
  codec:
    max-in-memory-size: 16MB 
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Tự động tìm service trên Eureka
          #lower-case-service-id: true # Chuyển tên service thành chữ thường (AUTH-SERVICE -> auth-service)
      
      # CẤU HÌNH CORS 
      #globalcors:
      #  cors-configurations:
      #    '[/**]':
      #      allowedOriginPatterns: "*" 
      #      allowedMethods: "*"
      #      allowedHeaders: "*"
      #      allowCredentials: true 

      routes:
        # --- AUTH SERVICE ---
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        
        # --- ACCOUNT SERVICE ---
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/account/**
        
        # --- TRANSACTION SERVICE ---
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/v1/transaction/**

        # --- NOTIFICATION SERVICE ---
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/** 
        
        # WebSocket Route
        - id: notification-service-ws
          uri: lb:ws://NOTIFICATION-SERVICE
          predicates:
            - Path=/ws/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: HS256

# --- CẤU HÌNH EUREKA CLIENT ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true # Cho phép Eureka kiểm tra sức khỏe Gateway
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

# Custom Config
app:
  jwtSecret: "mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm" 
  jwtCookieName: springBootEcom

# --- CẬP NHẬT: HEALTH CHECK ---
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, gateway # Thêm 'gateway' để xem route
  endpoint:
    health:
      show-details: always # Hiển thị chi tiết lỗi nếu có
    gateway:
      enabled: true # Cho phép xem danh sách route qua Actuator