server:
  port: 10004

spring:
  application:
    name: transaction-service
  
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction
    username: postgres
    password: huypd123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Producer Config
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Key là String
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Value là JSON (SỬA Ở ĐÂY: Đừng dùng StringSerializer cho Object)
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      # Thêm thông tin Type để Consumer biết map vào class nào
      spring.json.add.type.headers: true 

  # Redis Config
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 2s
      timeout: 1s
  # Cache Config
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

  # Mail Config
  mail:
    host: mail-dev
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# Custom Config
application:
  config:
    account-url: http://localhost:10003/api/v1/account
    auth-url: http://localhost:10003/api/v1/auth
    kafka:
      # SỬA Ở ĐÂY: Phải trùng tên với bên Notification
      transaction-topic: transaction-events 
      retry-interval-ms: 1000
      max-retries: 3